import type { LucideIcon } from "lucide-react";
import {
  BadgePercent,
  BarChart3,
  Boxes,
  Building2,
  ChartColumn,
  CircleDollarSign,
  ClipboardList,
  FileSpreadsheet,
  Gift,
  Megaphone,
  Network,
  Package2,
  PackageSearch,
  Repeat2,
  RotateCcw,
  ScanBarcode,
  ShieldCheck,
  ShoppingCart,
  Sparkles,
  Store,
  TriangleAlert,
  UsersRound,
  Wallet,
  Warehouse,
  Workflow,
} from "lucide-react";

export const iconMap = {
  alert: TriangleAlert,
  barcode: ScanBarcode,
  boxes: Boxes,
  branches: Building2,
  building: Building2,
  campaign: Megaphone,
  cash: Wallet,
  catalog: ClipboardList,
  chart: ChartColumn,
  checkout: ShoppingCart,
  control: CircleDollarSign,
  insight: BarChart3,
  inventory: PackageSearch,
  loyalty: Gift,
  megaphone: Megaphone,
  network: Network,
  offers: BadgePercent,
  package: Package2,
  repeat: Repeat2,
  returns: RotateCcw,
  shield: ShieldCheck,
  spark: Sparkles,
  spreadsheet: FileSpreadsheet,
  staff: UsersRound,
  store: Store,
  tag: BadgePercent,
  warehouse: Warehouse,
  workflow: Workflow,
} satisfies Record<string, LucideIcon>;

export type IconName = keyof typeof iconMap;
